const ISL_GOOD_MORNING = (ref) => {
  const compoundSteps = [];
  const animations = [];
  let step = [];
  step.push(["mixamorigRightHandIndex1", "rotation", "z", Math.PI / 2, "+"]);
  step.push(["mixamorigRightHandIndex2", "rotation", "z", Math.PI / 2, "+"]);
  step.push(["mixamorigRightHandIndex3", "rotation", "z", Math.PI / 2, "+"]);
  step.push(["mixamorigRightHandMiddle1", "rotation", "z", Math.PI / 2, "+"]);
  step.push(["mixamorigRightHandMiddle2", "rotation", "z", Math.PI / 2, "+"]);
  step.push(["mixamorigRightHandMiddle3", "rotation", "z", Math.PI / 2, "+"]);
  step.push(["mixamorigRightHandRing1", "rotation", "z", Math.PI / 2, "+"]);
  step.push(["mixamorigRightHandRing2", "rotation", "z", Math.PI / 2, "+"]);
  step.push(["mixamorigRightHandRing3", "rotation", "z", Math.PI / 2, "+"]);
  step.push(["mixamorigRightHandPinky1", "rotation", "z", Math.PI / 2, "+"]);
  step.push(["mixamorigRightHandPinky2", "rotation", "z", Math.PI / 2, "+"]);
  step.push(["mixamorigRightHandPinky3", "rotation", "z", Math.PI / 2, "+"]);
  step.push(["mixamorigRightHandThumb1", "rotation", "x", -Math.PI / 5, "-"]);
  step.push(["mixamorigRightHandThumb2", "rotation", "y", 0, "+"]);
  step.push(["mixamorigRightArm", "rotation", "x", -Math.PI / 3.8, "-"]);
  step.push(["mixamorigRightArm", "rotation", "z", Math.PI / 4, "-"]);
  step.push(["mixamorigRightForeArm", "rotation", "z", Math.PI / 3.5, "+"]);
  step.push(["mixamorigRightForeArm", "rotation", "y", Math.PI / 2.2, "-"]);
  step.push(["mixamorigRightHand", "rotation", "x", Math.PI / 10, "+"]);
  step.push(["mixamorigRightHand", "rotation", "y", -Math.PI / 8, "-"]);
  step.push(["mixamorigRightHand", "rotation", "z", Math.PI / 6, "+"]);
  animations.push(step);
  compoundSteps.push({ word: "GOOD", token: "GOOD", isWordEnd: false, bones: step });
  step = [];
  step.push(["mixamorigRightArm", "rotation", "x", -Math.PI / 3.2, "+"]);
  step.push(["mixamorigRightForeArm", "rotation", "z", Math.PI / 4.8, "-"]);
  step.push(["mixamorigRightHand", "rotation", "x", Math.PI / 8, "-"]);
  step.push(["mixamorigRightHand", "rotation", "y", -Math.PI / 6, "-"]);
  step.push(["mixamorigNeck", "rotation", "x", Math.PI / 6, "+"]);
  animations.push(step);
  compoundSteps.push({ word: "GOOD", token: "GOOD", isWordEnd: false, bones: step });
  step = [];
  step.push(["mixamorigRightHand", "rotation", "z", Math.PI / 6, "+"]);
  step.push(["mixamorigNeck", "rotation", "x", Math.PI / 7, "-"]);
  animations.push(step);
  compoundSteps.push({ word: "GOOD", token: "GOOD", isWordEnd: true, bones: step });
  step = [];
  step.push(["mixamorigNeck", "rotation", "x", Math.PI / 12, "-"]);
  step.push(["mixamorigRightHandIndex1", "rotation", "z", Math.PI / 8, "-"]);
  step.push(["mixamorigRightHandIndex2", "rotation", "z", 0, "-"]);
  step.push(["mixamorigRightHandIndex3", "rotation", "z", 0, "-"]);
  step.push(["mixamorigRightHandMiddle1", "rotation", "z", Math.PI / 8, "-"]);
  step.push(["mixamorigRightHandMiddle2", "rotation", "z", 0, "-"]);
  step.push(["mixamorigRightHandMiddle3", "rotation", "z", 0, "-"]);
  step.push(["mixamorigRightHandRing1", "rotation", "z", Math.PI / 8, "-"]);
  step.push(["mixamorigRightHandRing2", "rotation", "z", 0, "-"]);
  step.push(["mixamorigRightHandRing3", "rotation", "z", 0, "-"]);
  step.push(["mixamorigRightHandPinky1", "rotation", "z", Math.PI / 8, "-"]);
  step.push(["mixamorigRightHandPinky2", "rotation", "z", 0, "-"]);
  step.push(["mixamorigRightHandPinky3", "rotation", "z", 0, "-"]);
  step.push(["mixamorigRightHandThumb1", "rotation", "x", 0, "+"]);
  step.push(["mixamorigLeftArm", "rotation", "x", -Math.PI / 5, "-"]);
  step.push(["mixamorigLeftArm", "rotation", "z", -Math.PI / 4, "+"]);
  step.push(["mixamorigLeftForeArm", "rotation", "z", -Math.PI / 3, "-"]);
  step.push(["mixamorigLeftForeArm", "rotation", "y", -Math.PI / 2, "+"]);
  step.push(["mixamorigLeftHand", "rotation", "x", 0, "+"]);
  step.push(["mixamorigLeftHand", "rotation", "y", 0, "+"]);
  step.push(["mixamorigLeftHand", "rotation", "z", 0, "+"]);
  step.push(["mixamorigRightArm", "rotation", "x", -Math.PI / 6, "-"]);
  step.push(["mixamorigRightArm", "rotation", "z", Math.PI / 4, "-"]);
  step.push(["mixamorigRightForeArm", "rotation", "z", Math.PI / 4, "+"]);
  step.push(["mixamorigRightForeArm", "rotation", "y", Math.PI / 2, "-"]);
  step.push(["mixamorigRightHand", "rotation", "x", -Math.PI / 6, "-"]);
  step.push(["mixamorigRightHand", "rotation", "y", -Math.PI / 6, "-"]);
  step.push(["mixamorigRightHand", "rotation", "z", 0, "+"]);
  animations.push(step);
  compoundSteps.push({ word: "MORNING", token: "MORNING", isWordEnd: false, bones: step });
  step = [];
  step.push(["mixamorigRightArm", "rotation", "x", -Math.PI / 3.2, "-"]);
  step.push(["mixamorigRightArm", "rotation", "z", Math.PI / 5, "-"]);
  step.push(["mixamorigRightForeArm", "rotation", "z", Math.PI / 3, "+"]);
  step.push(["mixamorigRightForeArm", "rotation", "y", Math.PI / 2.2, "+"]);
  step.push(["mixamorigRightHand", "rotation", "x", 0, "+"]);
  step.push(["mixamorigRightHand", "rotation", "y", -Math.PI / 8, "+"]);
  step.push(["mixamorigRightHandIndex1", "rotation", "z", 0, "-"]);
  step.push(["mixamorigRightHandMiddle1", "rotation", "z", 0, "-"]);
  step.push(["mixamorigRightHandRing1", "rotation", "z", 0, "-"]);
  step.push(["mixamorigRightHandPinky1", "rotation", "z", 0, "-"]);
  animations.push(step);
  compoundSteps.push({ word: "MORNING", token: "MORNING", isWordEnd: false, bones: step });
  step = [];
  step.push(["mixamorigRightArm", "rotation", "x", -Math.PI / 2.5, "-"]);
  step.push(["mixamorigRightArm", "rotation", "z", Math.PI / 6, "-"]);
  step.push(["mixamorigRightForeArm", "rotation", "z", Math.PI / 3.8, "-"]);
  step.push(["mixamorigRightForeArm", "rotation", "y", Math.PI / 2.5, "+"]);
  step.push(["mixamorigRightHand", "rotation", "x", Math.PI / 6, "+"]);
  step.push(["mixamorigRightHand", "rotation", "y", -Math.PI / 6, "-"]);
  step.push(["mixamorigRightHand", "rotation", "z", Math.PI / 8, "+"]);
  step.push(["mixamorigNeck", "rotation", "x", Math.PI / 9, "+"]);
  animations.push(step);
  compoundSteps.push({ word: "MORNING", token: "MORNING", isWordEnd: false, bones: step });
  step = [];
  step.push(["mixamorigRightHand", "rotation", "z", Math.PI / 8, "+"]);
  animations.push(step);
  compoundSteps.push({ word: "MORNING", token: "MORNING", isWordEnd: true, bones: step });
  step = [];
  step.push(["mixamorigLeftArm", "rotation", "x", 0, "+"]);
  step.push(["mixamorigLeftArm", "rotation", "z", -Math.PI / 3, "-"]);
  step.push(["mixamorigLeftForeArm", "rotation", "z", 0, "+"]);
  step.push(["mixamorigLeftForeArm", "rotation", "y", -Math.PI / 1.5, "-"]);
  step.push(["mixamorigLeftHand", "rotation", "x", 0, "-"]);
  step.push(["mixamorigLeftHand", "rotation", "y", 0, "-"]);
  step.push(["mixamorigLeftHand", "rotation", "z", 0, "-"]);
  step.push(["mixamorigRightArm", "rotation", "x", 0, "+"]);
  step.push(["mixamorigRightArm", "rotation", "z", Math.PI / 3, "+"]);
  step.push(["mixamorigRightForeArm", "rotation", "z", 0, "-"]);
  step.push(["mixamorigRightForeArm", "rotation", "y", Math.PI / 1.5, "+"]);
  step.push(["mixamorigRightHand", "rotation", "x", 0, "-"]);
  step.push(["mixamorigRightHand", "rotation", "y", 0, "+"]);
  step.push(["mixamorigRightHand", "rotation", "z", 0, "-"]);
  step.push(["mixamorigNeck", "rotation", "x", Math.PI / 12, "-"]);
  animations.push(step);
  compoundSteps.push({
    word: "MORNING",
    token: "MORNING",
    isWordEnd: true,
    isReturnToRest: true,
    bones: step
  });
  ref.animations = animations;
  ref.compoundSteps = compoundSteps;
  if (ref.pending === false && typeof ref.animate === "function") {
    ref.pending = true;
    ref.animate();
  }
};
export {
  ISL_GOOD_MORNING
};
