const ISL_YES = (ref) => {
  let animations = [];
  animations.push(["mixamorigRightHandIndex1", "rotation", "z", Math.PI / 2, "+"]);
  animations.push(["mixamorigRightHandIndex2", "rotation", "z", Math.PI / 3, "+"]);
  animations.push(["mixamorigRightHandIndex3", "rotation", "z", Math.PI / 3, "+"]);
  animations.push(["mixamorigRightHandMiddle1", "rotation", "z", Math.PI / 2, "+"]);
  animations.push(["mixamorigRightHandMiddle2", "rotation", "z", Math.PI / 3, "+"]);
  animations.push(["mixamorigRightHandMiddle3", "rotation", "z", Math.PI / 3, "+"]);
  animations.push(["mixamorigRightHandRing1", "rotation", "z", Math.PI / 2, "+"]);
  animations.push(["mixamorigRightHandRing2", "rotation", "z", Math.PI / 3, "+"]);
  animations.push(["mixamorigRightHandRing3", "rotation", "z", Math.PI / 3, "+"]);
  animations.push(["mixamorigRightHandPinky1", "rotation", "z", Math.PI / 2, "+"]);
  animations.push(["mixamorigRightHandPinky2", "rotation", "z", Math.PI / 3, "+"]);
  animations.push(["mixamorigRightHandPinky3", "rotation", "z", Math.PI / 3, "+"]);
  animations.push(["mixamorigRightHandThumb1", "rotation", "x", Math.PI / 6, "+"]);
  animations.push(["mixamorigRightHandThumb2", "rotation", "y", -Math.PI / 3, "-"]);
  animations.push(["mixamorigRightArm", "rotation", "x", -Math.PI / 3.8, "-"]);
  animations.push(["mixamorigRightArm", "rotation", "z", Math.PI / 4.2, "-"]);
  animations.push(["mixamorigRightArm", "rotation", "y", Math.PI / 12, "+"]);
  animations.push(["mixamorigRightForeArm", "rotation", "z", Math.PI / 2.5, "+"]);
  animations.push(["mixamorigRightForeArm", "rotation", "y", Math.PI / 2, "-"]);
  animations.push(["mixamorigRightHand", "rotation", "x", Math.PI / 8, "+"]);
  animations.push(["mixamorigRightHand", "rotation", "y", 0, "+"]);
  animations.push(["mixamorigRightHand", "rotation", "z", 0, "+"]);
  animations.push(["mixamorigNeck", "rotation", "x", Math.PI / 14, "+"]);
  ref.animations.push(animations);
  animations = [];
  animations.push(["mixamorigRightHand", "rotation", "x", -Math.PI / 4.5, "-"]);
  animations.push(["mixamorigNeck", "rotation", "x", Math.PI / 6.5, "+"]);
  ref.animations.push(animations);
  animations = [];
  animations.push(["mixamorigRightHand", "rotation", "x", Math.PI / 10, "+"]);
  animations.push(["mixamorigNeck", "rotation", "x", Math.PI / 12, "-"]);
  ref.animations.push(animations);
  animations = [];
  animations.push(["mixamorigRightHand", "rotation", "x", -Math.PI / 4.5, "-"]);
  animations.push(["mixamorigNeck", "rotation", "x", Math.PI / 6, "+"]);
  ref.animations.push(animations);
  animations = [];
  animations.push(["mixamorigRightHandIndex1", "rotation", "z", 0, "-"]);
  animations.push(["mixamorigRightHandIndex2", "rotation", "z", 0, "-"]);
  animations.push(["mixamorigRightHandIndex3", "rotation", "z", 0, "-"]);
  animations.push(["mixamorigRightHandMiddle1", "rotation", "z", 0, "-"]);
  animations.push(["mixamorigRightHandMiddle2", "rotation", "z", 0, "-"]);
  animations.push(["mixamorigRightHandMiddle3", "rotation", "z", 0, "-"]);
  animations.push(["mixamorigRightHandRing1", "rotation", "z", 0, "-"]);
  animations.push(["mixamorigRightHandRing2", "rotation", "z", 0, "-"]);
  animations.push(["mixamorigRightHandRing3", "rotation", "z", 0, "-"]);
  animations.push(["mixamorigRightHandPinky1", "rotation", "z", 0, "-"]);
  animations.push(["mixamorigRightHandPinky2", "rotation", "z", 0, "-"]);
  animations.push(["mixamorigRightHandPinky3", "rotation", "z", 0, "-"]);
  animations.push(["mixamorigRightHandThumb1", "rotation", "x", 0, "-"]);
  animations.push(["mixamorigRightHandThumb2", "rotation", "y", 0, "+"]);
  animations.push(["mixamorigRightHand", "rotation", "x", 0, "+"]);
  animations.push(["mixamorigRightHand", "rotation", "y", 0, "+"]);
  animations.push(["mixamorigRightHand", "rotation", "z", 0, "-"]);
  animations.push(["mixamorigRightArm", "rotation", "x", 0, "+"]);
  animations.push(["mixamorigRightArm", "rotation", "y", 0, "-"]);
  animations.push(["mixamorigRightArm", "rotation", "z", Math.PI / 3, "+"]);
  animations.push(["mixamorigRightForeArm", "rotation", "z", 0, "-"]);
  animations.push(["mixamorigRightForeArm", "rotation", "y", Math.PI / 1.5, "+"]);
  animations.push(["mixamorigNeck", "rotation", "x", Math.PI / 12, "-"]);
  ref.animations.push(animations);
  if (ref.pending === false && typeof ref.animate === "function") {
    ref.pending = true;
    ref.animate();
  }
};
export {
  ISL_YES
};
