// services/webrtcService.js - Robust WebRTC Peer-to-Peer Video Stream Relay
// Connects Deaf Person camera stream to Admin "CITIZEN LIVE FEED" across independent devices/laptops
// Features: Dual-channel signaling, state guards against renegotiation storms, Unified Plan track recovery,
// autoplay-safe video attachment, and comprehensive connection diagnostics.

import { communicationService } from './communicationService.js';

const ICE_SERVERS = [
  { urls: 'stun:stun.l.google.com:19302' },
  { urls: 'stun:stun1.l.google.com:19302' },
  { urls: 'stun:stun2.l.google.com:19302' },
  { urls: 'stun:stun3.l.google.com:19302' },
  { urls: 'stun:stun4.l.google.com:19302' }
];

class WebRTCService {
  constructor() {
    this.instanceId = 'peer_' + Math.random().toString(36).substr(2, 7);
    this.role = null; // 'BROADCASTER' | 'RECEIVER' | null
    this.stream = null;
    this.remoteStream = null;
    this.videoElement = null;
    this.onStatusChange = null;

    this.senderPC = null;
    this.receiverPC = null;

    // Session / stream generation tracking
    this.broadcasterSessionId = null;      // Generated by broadcaster on publishStream
    this.activeBroadcasterSessionId = null; // Tracked by receiver from stream announcements / offers

    this.broadcasterQueuedCandidates = [];
    this.receiverQueuedCandidates = [];
    this.seenMessageIds = new Set();
    this.heartbeatTimer = null;
    this.requestRetryTimer = null;
    this.isNegotiating = false;

    this.initSignaling();
  }

  // Diagnostic logging header with peer ID, session ID, role, connection states, and timestamp
  getDiagHeader() {
    const ws = communicationService.ws;
    const wsState = ws ? ['CONNECTING', 'OPEN', 'CLOSING', 'CLOSED'][ws.readyState] || 'UNKNOWN' : 'NO_WS';
    const pc = this.role === 'RECEIVER' ? this.receiverPC : this.senderPC;
    const pcIce = pc?.iceConnectionState || 'none';
    const pcConn = pc?.connectionState || 'none';
    const pcSig = pc?.signalingState || 'none';
    const sess = this.broadcasterSessionId || this.activeBroadcasterSessionId || 'none';
    const stActive = Boolean(
      this.role === 'BROADCASTER'
        ? (this.stream && this.stream.active)
        : (this.remoteStream && this.remoteStream.active)
    );
    return `[WebRTC ${this.role || 'PEER'}][${this.instanceId}][sess=${sess}][ws=${wsState}][ice=${pcIce}, conn=${pcConn}, sig=${pcSig}][active=${stActive}][${new Date().toISOString()}]`;
  }

  // Dual-transport signaling: WebSocket (cross-device) + BroadcastChannel & localStorage (same-machine fallback)
  initSignaling() {
    const rtcEvents = [
      'RTC_OFFER',
      'RTC_ANSWER',
      'ICE_CANDIDATE',
      'RTC_REQUEST_STREAM',
      'RTC_STREAM_READY',
      'RTC_STREAM_STOPPED',
      'REQUEST_STREAM',
      'BROADCASTER_ANNOUNCE',
      'STREAM_OFFLINE',
      'PEER_CONNECTED'
    ];

    rtcEvents.forEach((evt) => {
      communicationService.on(evt, (payload) => {
        const data = payload && payload.type ? payload : { ...(payload || {}), type: evt };
        this.handleSignalingMessage(data);
      });
    });

    if (typeof window === 'undefined') return;

    // Same-machine fallback: BroadcastChannel
    try {
      this.channel = new BroadcastChannel('signbridge_webrtc_channel_v3');
      this.channel.onmessage = (event) => {
        if (event.data) {
          this.handleSignalingMessage(event.data);
        }
      };
    } catch (e) {
      console.warn('[WebRTC] BroadcastChannel unavailable:', e);
    }

    // Same-machine fallback: storage event
    window.addEventListener('storage', (event) => {
      if (event.key === 'signbridge_rtc_sig_msg' && event.newValue) {
        try {
          const data = JSON.parse(event.newValue);
          this.handleSignalingMessage(data);
        } catch (e) {}
      }
    });
  }

  sendSignaling(message) {
    if (!message) return;

    let eventType = message.type;
    if (eventType === 'REQUEST_STREAM') eventType = 'RTC_REQUEST_STREAM';
    if (eventType === 'BROADCASTER_ANNOUNCE') eventType = 'RTC_STREAM_READY';
    if (eventType === 'STREAM_OFFLINE') eventType = 'RTC_STREAM_STOPPED';

    const msgWithId = {
      ...message,
      type: eventType,
      id: message.id || ('sig_' + Date.now() + '_' + Math.random().toString(36).substr(2, 6)),
      senderInstanceId: message.senderInstanceId || this.instanceId,
      streamSessionId: message.streamSessionId || (this.role === 'BROADCASTER' ? this.broadcasterSessionId : this.activeBroadcasterSessionId) || null,
      timestamp: message.timestamp || Date.now()
    };
    this.seenMessageIds.add(msgWithId.id);

    // 1. Cross-Device Signaling via Render WebSocket
    communicationService.sendWsDirect(eventType, msgWithId);

    // 2. Same-machine local fallback: BroadcastChannel
    if (this.channel) {
      try {
        this.channel.postMessage(msgWithId);
      } catch (e) {}
    }

    // 3. Same-machine local fallback: localStorage ping
    try {
      if (typeof localStorage !== 'undefined') {
        localStorage.setItem('signbridge_rtc_sig_msg', JSON.stringify(msgWithId));
      }
    } catch (e) {}
  }

  async handleSignalingMessage(data) {
    if (!data || !data.type) return;
    if (data.id) {
      if (this.seenMessageIds.has(data.id)) return;
      this.seenMessageIds.add(data.id);

      if (this.seenMessageIds.size > 300) {
        const first = this.seenMessageIds.values().next().value;
        this.seenMessageIds.delete(first);
      }
    }

    switch (data.type) {
      // Opposite peer connected to room -> trigger renegotiation if ready
      case 'PEER_CONNECTED':
        if (this.role === 'BROADCASTER' && this.stream && this.stream.active) {
          console.log(`${this.getDiagHeader()} Opposite peer connected. Checking broadcaster connection state...`);
          if (this.isBroadcasterConnectionActiveOrConnecting()) {
            console.log(`${this.getDiagHeader()} Broadcaster connection active or establishing. Preserving senderPC, announcing stream presence.`);
            this.sendSignaling({
              type: 'RTC_STREAM_READY',
              streamSessionId: this.broadcasterSessionId,
              streamId: this.stream.id
            });
            return;
          }
          await this.startBroadcasterOffer('peer_connected');
        } else if (this.role === 'RECEIVER') {
          if (this.isReceiverConnectionActiveOrConnecting()) {
            console.log(`${this.getDiagHeader()} Receiver connection already active or connecting. Preserving receiverPC.`);
            return;
          }
          console.log(`${this.getDiagHeader()} Opposite peer connected. Requesting stream...`);
          this.sendSignaling({ type: 'RTC_REQUEST_STREAM' });
        }
        break;

      // Admin requests stream from Deaf Person broadcaster
      case 'RTC_REQUEST_STREAM':
      case 'REQUEST_STREAM':
        if (this.role === 'BROADCASTER' && this.stream && this.stream.active) {
          console.log(`${this.getDiagHeader()} Received REQUEST_STREAM from Admin.`);
          if (this.isBroadcasterConnectionActiveOrConnecting()) {
            console.log(`${this.getDiagHeader()} Broadcaster connection active or in-progress. Preserving senderPC, skipping redundant offer.`);
            this.sendSignaling({
              type: 'RTC_STREAM_READY',
              streamSessionId: this.broadcasterSessionId,
              streamId: this.stream.id
            });
            return;
          }
          await this.startBroadcasterOffer('request_stream');
        }
        break;

      // Deaf broadcaster announces stream presence
      case 'RTC_STREAM_READY':
      case 'BROADCASTER_ANNOUNCE':
        if (this.role === 'RECEIVER') {
          if (data.streamSessionId) {
            this.activeBroadcasterSessionId = data.streamSessionId;
          }
          if (this.isReceiverConnectionActiveOrConnecting()) {
            console.log(`${this.getDiagHeader()} Broadcaster announced active stream for session ${data.streamSessionId || 'legacy'}, receiver already connected/connecting.`);
            return; // Already connecting or streaming cleanly
          }
          console.log(`${this.getDiagHeader()} Detected active broadcaster session (${data.streamSessionId || 'legacy'}). Requesting stream...`);
          this.sendSignaling({
            type: 'RTC_REQUEST_STREAM',
            streamSessionId: data.streamSessionId || null
          });
        }
        break;

      // Receiver receives Offer from Broadcaster
      case 'RTC_OFFER':
        if (this.role === 'RECEIVER') {
          console.log(`${this.getDiagHeader()} Received RTC_OFFER for session: ${data.streamSessionId || 'legacy'}`);
          await this.handleRemoteOffer(data.sdp, data.streamSessionId, data.streamId);
        }
        break;

      // Broadcaster receives Answer from Receiver
      case 'RTC_ANSWER':
        if (this.role === 'BROADCASTER' && this.senderPC) {
          if (data.streamSessionId && this.broadcasterSessionId && data.streamSessionId !== this.broadcasterSessionId) {
            console.warn(`${this.getDiagHeader()} Ignoring RTC_ANSWER for mismatched session: incoming=${data.streamSessionId} !== current=${this.broadcasterSessionId}`);
            return;
          }
          console.log(`${this.getDiagHeader()} Received RTC_ANSWER.`);
          await this.handleRemoteAnswer(data.sdp);
        }
        break;

      // ICE Candidates exchange
      case 'ICE_CANDIDATE':
        if (data.streamSessionId) {
          if (this.role === 'RECEIVER' && this.activeBroadcasterSessionId && data.streamSessionId !== this.activeBroadcasterSessionId) {
            console.log(`${this.getDiagHeader()} Discarding stale ICE candidate from past session: ${data.streamSessionId}`);
            return;
          }
          if (this.role === 'BROADCASTER' && this.broadcasterSessionId && data.streamSessionId !== this.broadcasterSessionId) {
            console.log(`${this.getDiagHeader()} Discarding stale ICE candidate from past session: ${data.streamSessionId}`);
            return;
          }
        }
        await this.handleIncomingIceCandidate(data);
        break;

      // Broadcaster stopped camera
      case 'RTC_STREAM_STOPPED':
      case 'STREAM_OFFLINE':
        if (this.role === 'RECEIVER') {
          console.log(`${this.getDiagHeader()} Received RTC_STREAM_STOPPED: incomingSessionId=${data.streamSessionId}, currentSessionId=${this.activeBroadcasterSessionId}, incomingStreamId=${data.streamId}, reason=${data.reason || 'unspecified'}, caller=${data.caller || 'unknown'}`);

          // Guard 1: Origin/Role validation
          if ((data.origin && data.origin !== 'broadcaster') || (data.senderRole && data.senderRole !== 'deaf' && data.senderRole !== 'system')) {
            console.log(`${this.getDiagHeader()} Ignoring non-broadcaster stream stopped event.`);
            break;
          }

          // Guard 2: Stale session ID rejection - A receiver must NEVER treat a stale RTC_STREAM_STOPPED from an old broadcaster session as a stop for the current active stream
          if (data.streamSessionId && this.activeBroadcasterSessionId && data.streamSessionId !== this.activeBroadcasterSessionId) {
            console.warn(`${this.getDiagHeader()} STALE RTC_STREAM_STOPPED REJECTED! Message session (${data.streamSessionId}) !== Active receiver session (${this.activeBroadcasterSessionId}). Preserving active stream.`);
            break;
          }

          // Guard 3: Stale stream ID rejection
          if (data.streamId && this.remoteStream && this.remoteStream.id && data.streamId !== this.remoteStream.id) {
            console.warn(`${this.getDiagHeader()} STALE RTC_STREAM_STOPPED REJECTED! Message stream (${data.streamId}) !== Active remoteStream (${this.remoteStream.id}). Preserving active stream.`);
            break;
          }

          // Guard 4: Untargeted / legacy message rejection when connection is active or in-progress connecting
          const isReceiverActive = this.isReceiverConnectionActiveOrConnecting();
          if (!data.streamSessionId && isReceiverActive) {
            console.warn(`${this.getDiagHeader()} UNTARGETED/LEGACY RTC_STREAM_STOPPED REJECTED! Receiver has active or connecting PeerConnection; ignoring unverified stop command.`);
            break;
          }

          // Legitimate stop: Teardown receiver state cleanly
          console.log(`${this.getDiagHeader()} Processing legitimate RTC_STREAM_STOPPED for session: ${data.streamSessionId || this.activeBroadcasterSessionId}, reason: ${data.reason || 'unspecified'}`);
          this.activeBroadcasterSessionId = null;
          this.remoteStream = null;
          let el = this.videoElement || (typeof document !== 'undefined' ? document.getElementById('admin-camera-video') : null);
          if (el) {
            el.srcObject = null;
          }
          if (this.receiverPC) {
            try { this.receiverPC.close(); } catch (e) {}
            this.receiverPC = null;
          }
          if (this.onStatusChange) {
            this.onStatusChange(false, null);
          }
        }
        break;
    }
  }

  // Check if existing broadcaster senderPC is active or in-progress connecting
  isBroadcasterConnectionActiveOrConnecting() {
    if (!this.senderPC) return false;
    if (this.isNegotiating) return true;
    const ice = this.senderPC.iceConnectionState;
    const conn = this.senderPC.connectionState;
    const sig = this.senderPC.signalingState;

    // Active or in-progress states that must be preserved
    if (ice === 'connected' || ice === 'completed' || conn === 'connected') {
      return true;
    }
    if (sig === 'have-local-offer') {
      return true;
    }
    if (ice === 'checking' || conn === 'connecting' || ice === 'gathering') {
      return true;
    }
    return false;
  }

  // Check if existing receiver receiverPC is active or in-progress connecting
  isReceiverConnectionActiveOrConnecting() {
    if (!this.receiverPC) return false;
    const ice = this.receiverPC.iceConnectionState;
    const conn = this.receiverPC.connectionState;
    const sig = this.receiverPC.signalingState;

    if (ice === 'connected' || ice === 'completed' || conn === 'connected') {
      if (this.remoteStream && this.remoteStream.active) return true;
    }
    if (ice === 'checking' || conn === 'connecting' || sig === 'have-remote-offer' || ice === 'gathering') {
      return true;
    }
    return false;
  }

  // =========================================================================
  // 1. BROADCASTER ROLE (DEAF PERSON PAGE)
  // =========================================================================
  publishStream(stream, reason = 'publishStream') {
    if (!stream) return;
    const liveTracks = stream.getVideoTracks().filter((t) => t.readyState === 'live');

    // Generate unique session generation ID for this broadcast lifecycle
    this.broadcasterSessionId = 'sess_' + Date.now() + '_' + Math.random().toString(36).substr(2, 6);
    this.role = 'BROADCASTER';
    this.stream = stream;

    console.log(`${this.getDiagHeader()} Publishing stream: ${stream.id}, reason: ${reason}, Live video tracks: ${liveTracks.length}`);

    // Periodic announcement heartbeat so Admin knows stream is alive
    if (this.heartbeatTimer) clearInterval(this.heartbeatTimer);
    this.heartbeatTimer = setInterval(() => {
      if (this.stream && this.stream.active) {
        this.sendSignaling({
          type: 'RTC_STREAM_READY',
          streamSessionId: this.broadcasterSessionId,
          streamId: this.stream.id
        });
      }
    }, 4000);

    // Announce immediately and initiate offer
    this.sendSignaling({
      type: 'RTC_STREAM_READY',
      streamSessionId: this.broadcasterSessionId,
      streamId: this.stream.id
    });
    return this.startBroadcasterOffer(reason);
  }

  async startBroadcasterOffer(triggerReason = 'initial_publish') {
    if (!this.stream || !this.stream.active) return;
    if (this.isNegotiating) {
      console.log(`${this.getDiagHeader()} Negotiation already in flight, skipping.`);
      return;
    }

    try {
      this.isNegotiating = true;

      // Guard: do not destroy an already active, connected, or in-progress PeerConnection
      if (this.senderPC) {
        if (this.isBroadcasterConnectionActiveOrConnecting()) {
          console.log(`${this.getDiagHeader()} Broadcaster connection active or establishing. Preserving senderPC.`);
          this.sendSignaling({
            type: 'RTC_STREAM_READY',
            streamSessionId: this.broadcasterSessionId,
            streamId: this.stream.id
          });
          this.isNegotiating = false;
          return;
        }

        // Previous connection failed or disconnected -> close cleanly before recreating
        try { this.senderPC.close(); } catch (e) {}
        this.senderPC = null;
      }

      console.log(`${this.getDiagHeader()} Creating new RTCPeerConnection for broadcaster session: ${this.broadcasterSessionId}, trigger: ${triggerReason}...`);
      this.broadcasterQueuedCandidates = [];

      this.senderPC = new RTCPeerConnection({
        iceServers: ICE_SERVERS,
        iceCandidatePoolSize: 2
      });

      // Diagnostics & state listeners
      this.senderPC.onsignalingstatechange = () => {
        console.log(`${this.getDiagHeader()} senderPC signalingState: ${this.senderPC?.signalingState}`);
      };

      this.senderPC.oniceconnectionstatechange = () => {
        console.log(`${this.getDiagHeader()} senderPC iceConnectionState: ${this.senderPC?.iceConnectionState}`);
      };

      this.senderPC.onconnectionstatechange = () => {
        console.log(`${this.getDiagHeader()} senderPC connectionState: ${this.senderPC?.connectionState}`);
      };

      this.senderPC.onicegatheringstatechange = () => {
        console.log(`${this.getDiagHeader()} senderPC iceGatheringState: ${this.senderPC?.iceGatheringState}`);
      };

      // Add camera video tracks to connection
      const videoTracks = this.stream.getVideoTracks().filter((t) => t.readyState === 'live');
      if (videoTracks.length === 0) {
        console.warn(`${this.getDiagHeader()} Warning: No live video tracks found in stream!`);
      }

      videoTracks.forEach((track) => {
        const sender = this.senderPC.addTrack(track, this.stream);
        console.log(`${this.getDiagHeader()} Added track to senderPC: ${track.kind} ${track.id}, Sender confirmed: ${Boolean(sender)}`);
      });

      console.log(
        `${this.getDiagHeader()} Active senders count: ${this.senderPC.getSenders().length}`,
        this.senderPC.getSenders().map((s) => ({
          kind: s.track?.kind,
          id: s.track?.id,
          readyState: s.track?.readyState
        }))
      );

      // Send local ICE candidates to Admin receiver
      this.senderPC.onicecandidate = (event) => {
        if (event.candidate) {
          const candidateData = event.candidate.toJSON ? event.candidate.toJSON() : event.candidate;
          console.log(`${this.getDiagHeader()} Gathered local ICE candidate: ${candidateData.candidate?.substring(0, 45)}...`);
          this.sendSignaling({
            type: 'ICE_CANDIDATE',
            origin: 'broadcaster',
            candidate: candidateData,
            streamSessionId: this.broadcasterSessionId,
            streamId: this.stream?.id
          });
        } else {
          console.log(`${this.getDiagHeader()} ICE candidate gathering complete (candidate=null).`);
        }
      };

      // Create and send SDP Offer
      const offer = await this.senderPC.createOffer({
        offerToReceiveAudio: false,
        offerToReceiveVideo: false
      });

      console.log(`${this.getDiagHeader()} Offer created. Contains m=video: ${offer.sdp?.includes('m=video')}`);
      await this.senderPC.setLocalDescription(offer);
      console.log(`${this.getDiagHeader()} Local description set (offer). signalingState: ${this.senderPC.signalingState}`);

      this.sendSignaling({
        type: 'RTC_OFFER',
        sdp: offer,
        streamSessionId: this.broadcasterSessionId,
        streamId: this.stream.id
      });
    } catch (err) {
      console.error(`${this.getDiagHeader()} Error creating offer:`, err);
    } finally {
      this.isNegotiating = false;
    }
  }

  async handleRemoteAnswer(sdp) {
    if (!this.senderPC) {
      console.warn(`${this.getDiagHeader()} Cannot set remote answer: senderPC is null`);
      return;
    }

    try {
      if (this.senderPC.signalingState !== 'have-local-offer') {
        console.warn(`${this.getDiagHeader()} Unexpected signalingState for answer: ${this.senderPC.signalingState}. Ignoring.`);
        return;
      }

      await this.senderPC.setRemoteDescription(new RTCSessionDescription(sdp));
      console.log(`${this.getDiagHeader()} Remote answer applied successfully! signalingState: ${this.senderPC.signalingState}`);

      // Drain queued candidates that arrived before the answer was set
      while (this.broadcasterQueuedCandidates.length > 0) {
        const cand = this.broadcasterQueuedCandidates.shift();
        try {
          await this.senderPC.addIceCandidate(new RTCIceCandidate(cand));
          console.log(`${this.getDiagHeader()} Drained queued ICE candidate successfully.`);
        } catch (e) {
          console.warn(`${this.getDiagHeader()} Error applying queued candidate:`, e);
        }
      }
    } catch (err) {
      console.error(`${this.getDiagHeader()} Error setting remote answer:`, err);
    }
  }

  unpublishStream(caller = 'unknown', reason = 'unpublish') {
    const wasActiveBroadcaster = Boolean(this.role === 'BROADCASTER' && this.stream && this.stream.active !== false);
    const stoppingSessionId = this.broadcasterSessionId;
    const stoppingStreamId = this.stream ? this.stream.id : null;

    console.log(`${this.getDiagHeader()} unpublishStream called: caller=${caller}, reason=${reason}, wasActive=${wasActiveBroadcaster}, stoppingSessionId=${stoppingSessionId}`);

    if (this.heartbeatTimer) {
      clearInterval(this.heartbeatTimer);
      this.heartbeatTimer = null;
    }

    if (wasActiveBroadcaster) {
      console.log(`${this.getDiagHeader()} Sending RTC_STREAM_STOPPED for session: ${stoppingSessionId}, reason: ${reason}, caller: ${caller}`);
      this.sendSignaling({
        type: 'RTC_STREAM_STOPPED',
        origin: 'broadcaster',
        senderRole: 'deaf',
        streamSessionId: stoppingSessionId,
        streamId: stoppingStreamId,
        reason: reason,
        caller: caller
      });
    } else {
      console.log(`${this.getDiagHeader()} unpublishStream called without active broadcast role/stream; skipping RTC_STREAM_STOPPED broadcast.`);
    }

    if (this.senderPC) {
      try { this.senderPC.close(); } catch (e) {}
      this.senderPC = null;
    }
    this.stream = null;
    this.broadcasterSessionId = null;
    this.role = null;
    this.isNegotiating = false;
    this.broadcasterQueuedCandidates = [];
  }

  // =========================================================================
  // 2. RECEIVER ROLE (ADMIN / CITIZEN LIVE FEED)
  // =========================================================================
  subscribeStream(videoElement, onStatusChange) {
    console.log(`${this.getDiagHeader()} Subscribing Admin video element to stream...`);
    this.role = 'RECEIVER';
    this.videoElement = videoElement;
    this.onStatusChange = onStatusChange;

    // Check if stream already arrived or is active in same runtime (e.g. single tab SPA test)
    if (this.remoteStream && this.remoteStream.active) {
      this.attachStreamToVideo(this.remoteStream);
      if (this.onStatusChange) this.onStatusChange(true, this.remoteStream);
      return;
    }

    // Request stream from broadcaster immediately
    this.sendSignaling({ type: 'RTC_REQUEST_STREAM' });

    // Retry requesting stream periodically until stream arrives
    if (this.requestRetryTimer) clearInterval(this.requestRetryTimer);
    this.requestRetryTimer = setInterval(() => {
      if (!this.remoteStream || !this.remoteStream.active) {
        console.log(`${this.getDiagHeader()} Stream not active yet, sending RTC_REQUEST_STREAM retry...`);
        this.sendSignaling({
          type: 'RTC_REQUEST_STREAM',
          streamSessionId: this.activeBroadcasterSessionId || null
        });
      } else {
        clearInterval(this.requestRetryTimer);
        this.requestRetryTimer = null;
      }
    }, 2500);
  }

  async handleRemoteOffer(sdp, streamSessionId = null, streamId = null) {
    if (this.role !== 'RECEIVER') return;

    try {
      if (streamSessionId) {
        this.activeBroadcasterSessionId = streamSessionId;
      }

      // Guard: If we already have a connected receiverPC and live stream, do not tear down
      if (this.receiverPC) {
        // If offer is for SAME session and connection is already active/connecting, ignore duplicate offer
        if (streamSessionId && streamSessionId === this.activeBroadcasterSessionId && this.isReceiverConnectionActiveOrConnecting()) {
          console.log(`${this.getDiagHeader()} Already actively connected or connecting for session ${streamSessionId}. Ignoring duplicate offer.`);
          return;
        }

        const ice = this.receiverPC.iceConnectionState;
        const conn = this.receiverPC.connectionState;
        if ((ice === 'connected' || conn === 'connected') && this.remoteStream && this.remoteStream.active) {
          console.log(`${this.getDiagHeader()} Already actively connected and streaming. Ignoring duplicate offer.`);
          return;
        }

        try { this.receiverPC.close(); } catch (e) {}
        this.receiverPC = null;
      }

      console.log(`${this.getDiagHeader()} Creating new receiver RTCPeerConnection for session: ${this.activeBroadcasterSessionId}...`);
      this.receiverPC = new RTCPeerConnection({
        iceServers: ICE_SERVERS,
        iceCandidatePoolSize: 2
      });

      // Diagnostics & state listeners
      this.receiverPC.onsignalingstatechange = () => {
        console.log(`${this.getDiagHeader()} receiverPC signalingState: ${this.receiverPC?.signalingState}`);
      };

      this.receiverPC.oniceconnectionstatechange = () => {
        console.log(`${this.getDiagHeader()} receiverPC iceConnectionState: ${this.receiverPC?.iceConnectionState}`);
        if (this.receiverPC?.iceConnectionState === 'connected' || this.receiverPC?.iceConnectionState === 'completed') {
          if (this.onStatusChange) this.onStatusChange(true, this.remoteStream);
        } else if (this.receiverPC?.iceConnectionState === 'disconnected' || this.receiverPC?.iceConnectionState === 'failed') {
          console.warn(`${this.getDiagHeader()} ICE disconnected/failed. Re-requesting stream...`);
          this.sendSignaling({
            type: 'RTC_REQUEST_STREAM',
            streamSessionId: this.activeBroadcasterSessionId
          });
        }
      };

      this.receiverPC.onconnectionstatechange = () => {
        console.log(`${this.getDiagHeader()} receiverPC connectionState: ${this.receiverPC?.connectionState}`);
      };

      this.receiverPC.onicegatheringstatechange = () => {
        console.log(`${this.getDiagHeader()} receiverPC iceGatheringState: ${this.receiverPC?.iceGatheringState}`);
      };

      // Unified Plan ontrack: handle both stream-based and track-only payloads
      this.receiverPC.ontrack = (event) => {
        console.log(`${this.getDiagHeader()} Incoming video track received!`, {
          kind: event.track?.kind,
          id: event.track?.id,
          readyState: event.track?.readyState,
          streamsCount: event.streams ? event.streams.length : 0
        });

        let stream = event.streams && event.streams[0] ? event.streams[0] : null;
        if (!stream) {
          console.log(`${this.getDiagHeader()} event.streams[0] not present; assembling MediaStream from track`);
          if (!this.remoteStream) {
            this.remoteStream = new MediaStream();
          }
          if (!this.remoteStream.getTracks().some((t) => t.id === event.track.id)) {
            this.remoteStream.addTrack(event.track);
          }
          stream = this.remoteStream;
        } else {
          this.remoteStream = stream;
        }

        const videoTracks = stream.getVideoTracks();
        console.log(
          `${this.getDiagHeader()} Remote stream video tracks count: ${videoTracks.length}`,
          videoTracks.map((t) => ({ id: t.id, readyState: t.readyState, enabled: t.enabled }))
        );

        if (this.requestRetryTimer) {
          clearInterval(this.requestRetryTimer);
          this.requestRetryTimer = null;
        }

        this.attachStreamToVideo(stream);

        if (this.onStatusChange) {
          this.onStatusChange(true, stream);
        }
      };

      // Send local ICE candidates to Broadcaster
      this.receiverPC.onicecandidate = (event) => {
        if (event.candidate) {
          const candidateData = event.candidate.toJSON ? event.candidate.toJSON() : event.candidate;
          console.log(`${this.getDiagHeader()} Gathered local ICE candidate: ${candidateData.candidate?.substring(0, 45)}...`);
          this.sendSignaling({
            type: 'ICE_CANDIDATE',
            origin: 'receiver',
            candidate: candidateData,
            streamSessionId: this.activeBroadcasterSessionId,
            streamId: streamId
          });
        } else {
          console.log(`${this.getDiagHeader()} ICE candidate gathering complete (candidate=null).`);
        }
      };

      // Set Remote Description (the Offer from Deaf page)
      await this.receiverPC.setRemoteDescription(new RTCSessionDescription(sdp));
      console.log(`${this.getDiagHeader()} Remote description set (offer). signalingState: ${this.receiverPC.signalingState}`);

      // Drain queued candidates that arrived before the offer was set
      while (this.receiverQueuedCandidates.length > 0) {
        const cand = this.receiverQueuedCandidates.shift();
        try {
          await this.receiverPC.addIceCandidate(new RTCIceCandidate(cand));
          console.log(`${this.getDiagHeader()} Drained queued candidate successfully.`);
        } catch (e) {
          console.warn(`${this.getDiagHeader()} Error draining queued candidate:`, e);
        }
      }

      // Create and send SDP Answer back to Deaf page
      const answer = await this.receiverPC.createAnswer();
      await this.receiverPC.setLocalDescription(answer);
      console.log(`${this.getDiagHeader()} Local answer created and set. signalingState: ${this.receiverPC.signalingState}`);

      this.sendSignaling({
        type: 'RTC_ANSWER',
        sdp: answer,
        streamSessionId: this.activeBroadcasterSessionId,
        streamId: streamId
      });
    } catch (err) {
      console.error(`${this.getDiagHeader()} Error handling remote offer:`, err);
    }
  }

  attachStreamToVideo(stream) {
    if (!stream) return;

    // Look up live element if cached reference is detached or null
    let el = this.videoElement;
    if (!el || !el.isConnected) {
      if (typeof document !== 'undefined') {
        el = document.getElementById('admin-camera-video');
        if (el) this.videoElement = el;
      }
    }

    if (!el) {
      console.warn(`${this.getDiagHeader()} No DOM video element found to attach stream`);
      return;
    }

    // Guaranteed autoplay configuration
    el.autoplay = true;
    el.playsInline = true;
    el.muted = true;
    el.defaultMuted = true;
    el.setAttribute('autoplay', '');
    el.setAttribute('playsinline', '');
    el.setAttribute('muted', '');
    el.style.transform = 'none'; // Un-mirrored for Admin view
    el.style.objectFit = 'cover';

    if (el.srcObject !== stream) {
      console.log(`${this.getDiagHeader()} Attaching stream to Admin video element: ${stream.id}`);
      el.srcObject = stream;
      console.log(`${this.getDiagHeader()} Assigned srcObject to video element successfully`);
    } else {
      console.log(`${this.getDiagHeader()} video.srcObject already matches stream; preserving without reloading.`);
    }

    const playPromise = el.play();
    if (playPromise !== undefined) {
      playPromise
        .then(() => {
          console.log(`${this.getDiagHeader()} Admin video playback started successfully! Dimensions: ${el.videoWidth} x ${el.videoHeight}`);
          if (this.onStatusChange) this.onStatusChange(true, stream);
        })
        .catch((err) => {
          console.warn(`${this.getDiagHeader()} Auto-play was prevented, retrying muted...`, err);
          el.muted = true;
          el.defaultMuted = true;
          el.play().catch(() => {});
        });
    }
  }

  unsubscribeStream(reason = 'unsubscribeStream') {
    console.log(`${this.getDiagHeader()} Unsubscribing Admin stream: reason=${reason}`);
    if (this.requestRetryTimer) {
      clearInterval(this.requestRetryTimer);
      this.requestRetryTimer = null;
    }

    if (this.receiverPC) {
      try { this.receiverPC.close(); } catch (e) {}
      this.receiverPC = null;
    }

    if (this.videoElement) {
      this.videoElement.srcObject = null;
      this.videoElement = null;
    }

    this.remoteStream = null;
    this.activeBroadcasterSessionId = null;
    this.onStatusChange = null;
    this.role = null;
    this.receiverQueuedCandidates = [];
  }

  // =========================================================================
  // 3. CANDIDATE QUEUE DISPATCHER
  // =========================================================================
  async handleIncomingIceCandidate(data) {
    if (!data || !data.candidate) return;

    // Deterministic target selection based on this peer's role
    const targetPC = this.role === 'RECEIVER' ? this.receiverPC : this.senderPC;
    const queue = this.role === 'RECEIVER' ? this.receiverQueuedCandidates : this.broadcasterQueuedCandidates;

    if (!targetPC) {
      console.log(`[WebRTC ${this.role || 'PEER'}] Target PC not ready yet; queuing ICE candidate`);
      queue.push(data.candidate);
      return;
    }

    const hasRemote = targetPC.remoteDescription && targetPC.remoteDescription.type;
    if (hasRemote) {
      try {
        await targetPC.addIceCandidate(new RTCIceCandidate(data.candidate));
        console.log(`[WebRTC ${this.role}] Added ICE candidate successfully`);
      } catch (err) {
        console.warn(`[WebRTC ${this.role}] addIceCandidate error:`, err);
      }
    } else {
      console.log(`[WebRTC ${this.role}] Remote description not set yet; queuing ICE candidate`);
      queue.push(data.candidate);
    }
  }

  getRemoteStream() {
    return this.remoteStream;
  }
}

export const webrtcService = new WebRTCService();
